[build]
builder = "nixpacks"
buildCommand = "pnpm prisma:generate && pnpm build"

[deploy]
preDeployCommand = "pnpm prisma:migrate:deploy"
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

