services:
  - type: web
    name: edikit-api
    env: node
    buildCommand: pnpm install && pnpm prisma:generate && pnpm build
    preDeployCommand: pnpm prisma:migrate:deploy
    startCommand: pnpm start
